export const GET_SPENDINGS_SUCCESS = 'GET_SPENDINGS_SUCCESS';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_FAVOURITE_CATEGORIES_SUCCESS = 'GET_FAVOURITE_CATEGORIES_SUCCESS';
