export const GET_SPENDINGS_SUCCESS = 'GET_SPENDINGS_SUCCESS';
export const ADD_SPENDING_SUCCESS = 'ADD_SPENDING_SUCCESS';
export const DELETE_SPENDING_SUCCESS = 'DELETE_SPENDING_SUCCESS';
export const UPDATE_SPENDING_AMOUNT_SUCCESS = 'UPDATE_SPENDING_AMOUNT_SUCCESS';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_FAVOURITE_CATEGORIES_SUCCESS = 'GET_FAVOURITE_CATEGORIES_SUCCESS';
export const UPDATE_DATE = 'UPDATE_DATE';
